FROM eeacms/node:v4.2.2-1.1
ENV NODE_ENV 'dev'
ADD ./app/package.json /tmp/package.json
ADD ./README.md /tmp/README.md
RUN cd /tmp && npm install && mv /tmp/node_modules /node_modules
RUN npm install -g nodemon
ADD ./eea-searchserver /tmp/eea-searchserver
RUN npm install /tmp/eea-searchserver
ADD ./app /code
#ENTRYPOINT ["nodemon", "--watch", "code/", "/code/app.js"]
USER node